import { useEffect, useMemo, useState } from "react";
import { createMasterAssignment, getDesigns, getMasters, getOrders, getProductionOrder, linkDesignToOrder } from "../services/api";
import { ErrorState } from "../components/ErrorState";
import { LoadingState } from "../components/LoadingState";
import type { Design, Master, Order, ProductionOrder } from "../types";

const label=(v:string)=>v.replaceAll("_"," ");
export function ProductionPage(){
  const [orders,setOrders]=useState<Order[]>([]); const [orderId,setOrderId]=useState(""); const [production,setProduction]=useState<ProductionOrder|null>(null);
  const [designs,setDesigns]=useState<Design[]>([]); const [masters,setMasters]=useState<Master[]>([]); const [selectedDesign,setSelectedDesign]=useState("");
  const [form,setForm]=useState({designId:"",size:"",masterId:"",quantity:"",notes:""}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  async function loadOrders(){try{setOrders((await getOrders()).data);setDesigns((await getDesigns()).data)}catch(e){setError(e instanceof Error?e.message:"Unable to load production data")}}
  async function loadOrder(id:string){if(!id){setProduction(null);return}try{const p=(await getProductionOrder(id)).data;setProduction(p);if(p.shop?.id)setMasters((await getMasters(p.shop.id)).data)}catch(e){setError(e instanceof Error?e.message:"Unable to load order production")}}
  useEffect(()=>{loadOrders()},[]);
  useEffect(()=>{loadOrder(orderId)},[orderId]);
  const availableDesigns=useMemo(()=>production?designs.filter(d=>d.garment===production.garment&&!production.designs.some(x=>x.designId===d.id)):[],[designs,production]);
  async function addDesign(){if(!orderId||!selectedDesign)return;setSaving(true);setError("");try{await linkDesignToOrder(orderId,selectedDesign);setSelectedDesign("");await loadOrder(orderId)}catch(e){setError(e instanceof Error?e.message:"Unable to link design")}finally{setSaving(false)}}
  async function assign(designId:string){if(!form.size||!form.masterId||!form.quantity)return;setSaving(true);setError("");try{await createMasterAssignment(designId,{masterId:form.masterId,size:form.size,quantity:Number(form.quantity),notes:form.notes||undefined});setForm(f=>({...f,quantity:"",notes:""}));await loadOrder(orderId)}catch(e){setError(e instanceof Error?e.message:"Unable to assign master")}finally{setSaving(false)}}
  if(!orders.length&&!error)return <LoadingState label="Loading production board…"/>;
  return <div className="mx-auto max-w-6xl space-y-5">
    <div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Production</p><h3 className="text-2xl font-semibold text-navy-900">Master assignments</h3><p className="text-sm text-slate-600">See who is working on each design and size. The same size can be split across multiple masters.</p></div>
    {error&&<ErrorState message={error}/>}
    <section className="rounded-xl border border-sand-100 bg-white p-5 shadow-sm"><label className="text-xs font-medium uppercase tracking-wide text-slate-500">Select order</label><select value={orderId} onChange={e=>setOrderId(e.target.value)} className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">Choose an order…</option>{orders.map(o=><option key={o.id} value={o.id}>{o.orderNo} · {o.customer.name} · {label(o.garment)} · {o.quantity} pcs</option>)}</select></section>
    {production&&<><section className="rounded-xl border border-sand-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs text-slate-500">{production.orderNo} · {production.shop?.name||"No shop"}</p><h4 className="mt-1 text-xl font-semibold text-navy-900">{production.customer.name}</h4><p className="text-sm text-slate-600">{production.description}</p></div><div className="rounded-lg bg-slate-50 px-4 py-3 text-right"><p className="text-xs text-slate-500">Total pieces</p><p className="text-lg font-semibold">{production.quantity}</p></div></div>
      <div className="mt-5 flex flex-wrap gap-2">{production.sizeBreakdowns.map(s=><span key={s.id} className="rounded-full border border-slate-200 px-3 py-1 text-xs font-medium">{s.size}: {s.quantity}</span>)}</div></section>
      <section className="rounded-xl border border-sand-100 bg-white p-5 shadow-sm"><h4 className="font-semibold text-navy-900">Attach design</h4><div className="mt-3 flex flex-col gap-2 sm:flex-row"><select value={selectedDesign} onChange={e=>setSelectedDesign(e.target.value)} className="flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">Choose design…</option>{availableDesigns.map(d=><option key={d.id} value={d.id}>{d.designNo} · {d.name}</option>)}</select><button disabled={!selectedDesign||saving} onClick={addDesign} className="rounded-md bg-navy-900 px-4 py-2 text-sm font-medium text-white">Attach design</button></div></section>
      {!production.shop&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Assign a stitching shop to this order before assigning masters.</div>}
      {production.designs.map(od=><DesignAssignmentCard key={od.id} od={od} production={production} masters={masters} form={form} setForm={setForm} saving={saving} onAssign={assign}/>)}
      {!production.designs.length&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No design is attached to this order yet. Attach a design above to start master assignment.</div>}
    </>}
  </div>
}
function DesignAssignmentCard({od,production,masters,form,setForm,saving,onAssign}:any){
  return <section className="rounded-xl border border-sand-100 bg-white p-5 shadow-sm"><div className="flex items-start gap-4">{od.design.imagePath?<img src={od.design.imagePath} alt="" className="h-16 w-16 rounded-lg object-cover"/>:<div className="flex h-16 w-16 items-center justify-center rounded-lg bg-slate-100 text-sm font-semibold text-slate-300">SP</div>}<div><p className="text-xs text-slate-500">{od.design.designNo}</p><h4 className="font-semibold text-navy-900">{od.design.name}</h4><p className="text-sm text-slate-600">{od.design.description||"Design linked to this order"}</p></div></div>
    <div className="mt-5 space-y-4">{production.sizeBreakdowns.map((s:any)=>{const rows=od.assignments.filter((a:any)=>a.size===s.size);const assigned=rows.reduce((n:any,a:any)=>n+a.quantity,0);const remaining=s.quantity-assigned;return <div key={s.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold">{s.size}</span><span className="ml-2 text-sm text-slate-500">{s.quantity} required</span></div><span className={"rounded-full px-2.5 py-1 text-xs font-medium "+(remaining===0?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{assigned} assigned · {remaining} remaining</span></div>
      {rows.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{rows.map((a:any)=><div key={a.id} className="rounded-md bg-slate-50 px-3 py-2 text-sm"><div className="flex justify-between"><span>{a.master.name}</span><strong>{a.quantity}</strong></div><p className="mt-1 text-[11px] text-slate-500">{a.startedAt?"Work started":"Not started"}</p></div>)}</div>}
      {remaining>0&&<div className="mt-3 grid gap-2 sm:grid-cols-4"><select value={form.size===s.size?form.masterId:""} onChange={e=>setForm((f:any)=>({...f,size:s.size,masterId:e.target.value}))} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">Master…</option>{masters.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input type="number" min="1" max={remaining} value={form.size===s.size?form.quantity:""} onChange={e=>setForm((f:any)=>({...f,size:s.size,quantity:e.target.value}))} placeholder={"Qty (max "+remaining+")"} className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input value={form.size===s.size?form.notes:""} onChange={e=>setForm((f:any)=>({...f,size:s.size,notes:e.target.value}))} placeholder="Note (optional)" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><button disabled={saving||form.size!==s.size||!form.masterId||!form.quantity} onClick={()=>onAssign(od.id)} className="rounded-md bg-emerald-700 px-3 py-2 text-sm font-medium text-white">Assign</button></div>}</div>})}</div>
  </section>
}
