import { useEffect, useState, type FormEvent } from "react";
import { createUser, getUsers, updateUser, type ManagedUser } from "../services/api";
export function UsersPage(){
 const [users,setUsers]=useState<ManagedUser[]>([]);const [form,setForm]=useState({name:"",email:"",password:"",role:"STAFF" as "OWNER"|"STAFF"});const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 const load=()=>getUsers().then(r=>setUsers(r.data)).catch(e=>setError(e.message));useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await createUser(form);setForm({name:"",email:"",password:"",role:"STAFF"});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create user");}finally{setSaving(false);}}
 return <div className="mx-auto max-w-5xl space-y-5"><section><p className="text-xs uppercase tracking-[.18em] text-slate-500">Administration</p><h3 className="mt-1 text-2xl font-semibold text-navy-900">Users</h3><p className="mt-1 text-sm text-slate-600">Manage who can access the application and financial information.</p></section>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <form onSubmit={submit} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="h-11 px-3"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" className="h-11 px-3"/><input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Password" className="h-11 px-3"/><div className="flex gap-2"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value as "OWNER"|"STAFF"})} className="h-11 flex-1 px-3"><option value="STAFF">Staff</option><option value="OWNER">Owner</option></select><button disabled={saving} className="rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white">{saving?"Saving…":"Add"}</button></div></form>
 <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-500"><th className="pb-3">Name</th><th className="pb-3">Email</th><th className="pb-3">Role</th><th className="pb-3">Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-slate-50 last:border-0"><td className="py-3 font-medium">{u.name}</td><td className="py-3">{u.email}</td><td className="py-3">{u.role}</td><td className="py-3"><button onClick={()=>void updateUser(u.id,{active:!u.active}).then(load)} className={"rounded-full px-2.5 py-1 text-xs font-semibold "+(u.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{u.active?"Active":"Inactive"}</button></td></tr>)}</tbody></table></div></section></div>;
}