import { useEffect, useState, type FormEvent } from "react";
import { createUser, deleteUser, getUsers, updateUser, type ManagedUser } from "../services/api";
export function UsersPage(){
 const [users,setUsers]=useState<ManagedUser[]>([]); const [form,setForm]=useState({name:"",username:"",password:"",role:"STAFF" as "ADMIN"|"STAFF"}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const load=()=>getUsers().then(r=>setUsers(r.data)).catch(e=>setError(e instanceof Error?e.message:"Unable to load users")); useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await createUser(form);setForm({name:"",username:"",password:"",role:"STAFF"});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create user");}finally{setSaving(false);}}
 async function remove(u:ManagedUser){if(!window.confirm("Delete user '"+u.username+"'? This cannot be undone."))return;setError("");try{await deleteUser(u.id);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to delete user");}}
 async function toggle(u:ManagedUser){setError("");try{await updateUser(u.id,{active:!u.active});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update user");}}
 async function changeRole(u:ManagedUser,role:"ADMIN"|"STAFF"){setError("");try{await updateUser(u.id,{role});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to change access");}}
 return <div className="mx-auto max-w-6xl space-y-5"><section><p className="text-xs uppercase tracking-[.18em] text-slate-500">Administration</p><h3 className="mt-1 text-2xl font-semibold text-navy-900">User management</h3><p className="mt-1 text-sm text-slate-600">Create users, assign Admin or Staff access, activate/deactivate accounts, and delete users by username.</p></section>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <form onSubmit={submit} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="h-11 rounded-md border px-3"/><input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="Username" className="h-11 rounded-md border px-3"/><input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Password" className="h-11 rounded-md border px-3"/><div className="flex gap-2"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value as "ADMIN"|"STAFF"})} className="h-11 flex-1 rounded-md border px-3"><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select><button disabled={saving} className="rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white">{saving?"Saving…":"Add"}</button></div></form>
 <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs text-slate-500"><th className="pb-3">Name</th><th className="pb-3">Username</th><th className="pb-3">Access</th><th className="pb-3">Status</th><th className="pb-3">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-slate-50 last:border-0"><td className="py-3 font-medium">{u.name}</td><td className="py-3 font-medium text-slate-700">{u.username}</td><td className="py-3"><select value={u.role} onChange={e=>void changeRole(u,e.target.value as "ADMIN"|"STAFF")} className="rounded-md border border-slate-200 px-2 py-1.5 text-xs"><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></td><td className="py-3"><button onClick={()=>void toggle(u)} className={"rounded-full px-2.5 py-1 text-xs font-semibold "+(u.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{u.active?"Active":"Inactive"}</button></td><td className="py-3"><button onClick={()=>void remove(u)} className="rounded-md border border-red-200 px-3 py-1.5 text-xs font-medium text-red-700">Delete</button></td></tr>)}</tbody></table></div></section></div>;
}